version: '3'
services:
  web:
    build: .
    ports:
      - 8087:4000
    depends_on:
      - mongoeva
    environment:
      - USERNAME
      - PASSWORD
  mongoeva:
    image: mongo:latest
    volumes:
      - ./dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $PASSWORD
